### PR TITLE
FEATURE : Add support for NaN and infinity representations

### PR DESCRIPTION
**Pull request by danilomendesdias**
Hi again.

This is a first attempt to solve https://github.com/crdoconnor/strictyaml/issues/121.

@crdoconnor, could you please give me an initial feedback so I can fix the code according to your expectations and style?

Thank you!

### CODE REVIEW

**Comment by danilomendesdias** [comment]
@crdoconnor I think this is ready now :)

let me know if there is something else I can do.

thanks!

**Comment by crdoconnor** [comment]
Thanks, I'll take a look later.

**Comment by crdoconnor** [comment]
Released onto pypi as version 1.1.0. Thank you for all of your hard work @danilomendesdias ! :tada: :tada: :tada:

**Comment by danilomendesdias** [comment]
It was fun to help with this. Thank you for your support and time to keep StrictYAML up to date.

About the documentation, I should have updated that with some examples and comments about the acceptable inputs and serializer outputs, but I totally forgot it. Sorry for that. I can help again as soon as I find another time slot.

**Comment by crdoconnor** [comment]
The documentation is supposed to be auto generating from the example
stories you amended.

**Comment by crdoconnor** [comment]
No worries on that I can take care of it. You've done more than enough,
thanks.

**Pull request merged**
