### PR TITLE
BUGFIX: Support None as Optional default (#62) , add default to Optional.__repr__

### PR DESCRIPTION
**Pull request by ntova**
#62 mentions that `None` is not supported as default value in Optional.
Fix this by adding a unique object and checking for identity when determining if the default value exists or not.

Also add the default value to `__repr__`

Btw: is there a timeline for when default values in Optionals will become stable? They haven't changed in the last two years.

### CODE REVIEW

**Comment by crdoconnor** [comment]
I'm super happy to support this use case. I think it's incredibly useful. However, I'm not sure if this is the right way.

Does this sound like it might work for you?

```
print(load("y: x", Map({
  Optional("x", default=lambda: None): EmptyNone() | Str(),
  "y": Str(),
})).data
{"x": None, "y": "x"}
```

**Comment by ntova** [comment]
Yeah, that would work excellent. A factory function would allow one to reuse a schema with mutable defaults easily. The only con would be the API break, but, as defaults a alpha anyway, this seems to be the better and more future proof approach :)

**Comment by crdoconnor** [comment]
The API break?

**Comment by ntova** [comment]
As I understood it, you were going to replace all defaults with factory functions, but you are just doing that for the `None` value. Sorry for the misunderstanding.
Ignore my answer above, I was thinking in too general terms :see_no_evil: 

Your solution would work just as well as mine, so just implement what you like better :)
- Advantage with my solution: more uniform across all default values
- Advantage with your solution: a simple `None` allows you to easily disable default values

**Comment by crdoconnor** [comment]
Actually I can't do it this way - it has to be reversible. If it's a lambda that's a bit ugly. I'm leaning towards this solution now:

    schema = Map({
      Optional("x", default_to_none=True): EmptyNone() | Str(),
      "y": Str(),
    }

    print(load("y: x", schema)).data
    {"x": None, "y": "x"}

    print(as_document({"x": None, "y": "x"}, schema).as_yaml())
    y: x

**Comment by ntova** [comment]
Yeah, I didn't think of the reverse way.
So Optional is then `Optional(validator, default=None, default_to_none=False)`? This would work, too.

Just as a question, what problems do you see with my solution in this PR?

**Comment by crdoconnor** [comment]
#1 It changed the default behavior (None currently means no default). This would break a ton of existing code. I also think the way it works right now works fine for most people.
#2 The use of Optional.NO_DEFAULT feels a little icky.
#3 There was no specification example (no hitch story).

default_to_none as a boolean parameter also feels a little icky though.

I'm leaning towards using "default_to_none" but using a different name. I'd ideally like a name where people who have no context glance at it an instantaneously know why it's there and what it's doing without having to look it up. I was mulling over:

* default_to_none
* always_include_key
* include_key
* "drop_key" where drop_key defaults to True, but you can override it to False. (my favorite thus far).

I'm afraid this mulling is making me take a little longer over this.

**Comment by shoogle** [comment]
What's the difference between not having a default verses having a default that is `None`?

**Comment by crdoconnor** [comment]
The differences is between parsing 'a: b' as {"a": "b"} and {"a": "b",
"missing key": None}


Apologies for the delay btw. Had some stuff to deal with recently. I
haven't forgotten about this though.

**Comment by crdoconnor** [comment]
I've fixed this and released in 1.2.0. Thanks for raising the issue (& the PR). Now, if you use drop_if_none=False, the key won't be dropped.

I'll update docs later.

**Pull request closed without merging**
