### PR TITLE
BUG: incorrect Optional() handling

### PR DESCRIPTION
**Pull request by bt2901**
BUG: validator._required_keys was incorrect

### CODE REVIEW

**Comment by crdoconnor** [comment]
How did you manage to invoke this bug?

**Comment by bt2901** [comment]
I invoked this bug in the middle of sorting out various problems related to `Optional` validator. To me, it appears to be unfinished at the moment.

I implemented some required functionality myself (outside of your library), but wasn't sure if that was the correct way to do it. On the contrary, `self._required_keys` issue definitely was a bug (and there was no easy workaround). Hence, this pull request.

So, my monkeypatch for `Optional` is:

```
import strictyaml
from strictyaml import Map, Str, Int, Bool, Seq, Any

from strictyaml import Validator

class Optional(Validator):
    def __init__(self, key, default=None):
        self.key = key
        self.default = default

    def __repr__(self):
        # TODO: Add default
        return u'Optional("{0}")'.format(self.key)
    
    def validate(self, chunk):
        val = chunk.contents
        # return self.key(val)
        #return chunk.contents
        return self.key.validate(chunk)
```

After that, run this:


```
local_schema = Map({
    'RegularizersModifierCube': Map({
        'num_iter': Int(), 
        'regularizer_parameters': Any(), 
        'reg_search': Optional(Any()), 
        'strategy': Optional(Any()), 
        'tracked_score_function': Optional(Any()), 
        'verbose': Optional(Bool()), 
        'selection': Seq(Str())
    })
})

yaml_string = '''
RegularizersModifierCube:
    num_iter: 5
    reg_search: add
    regularizer_parameters:
      regularizer_name: SmoothSparsePhiRegularizer
      tau_grid: []
    selection:
    - model.seed = 82019 and GoodinessMeasure -> max
    - model.seed = 322 and GoodinessMeasure -> max
    verbose: false
'''
strictyaml.dirty_load(yaml_string, local_schema, allow_flow_style=True)
```
and you will get

```
YAMLValidationError: while parsing a mapping
  in "<unicode string>", line 1, column 1:
    RegularizersModifierCube:
     ^ (line: 1)
required key(s) 'strategy', 'tracked_score_function' not found
  in "<unicode string>", line 10, column 1:
      verbose: 'false'
    ^ (line: 10)
```

**Comment by bt2901** [comment]
What's the status of this? Was my `Optional` hotfix correct or did I misapply it? If my approach is OK, I could add everything to PR.

**Comment by crdoconnor** [comment]
I'm still not really sure what the bug was that caused this. Could you provide a code snippet that invokes the bug that you're trying to fix?

**Comment by crdoconnor** [comment]
I don't merge anything that I don't have an accompanying failing story, although I'm happy to write the story myself if I can clearly see what the bug is.

**Comment by bt2901** [comment]
I have a question then.

Leaving my hotfix aside, let's take a look at the following YAML: 

```
yaml_string = '''
RegularizersModifierCube:
    num_iter: 5
    reg_search: add
    regularizer_parameters:
      regularizer_name: SmoothSparsePhiRegularizer
      tau_grid: []
    selection:
    - model.seed = 82019 and GoodinessMeasure -> max
    - model.seed = 322 and GoodinessMeasure -> max
    verbose: false
'''
```

and try to load it like this:

```
import strictyaml
from strictyaml import Map, Optional, Any, Int, Bool, Seq, Str

local_schema = Map({
    'RegularizersModifierCube': Map({
        'num_iter': Int(), 
        'regularizer_parameters': Any(), 
        'reg_search': Optional(Any()), 
        'strategy': Optional(Any()), 
        'tracked_score_function': Optional(Any()), 
        'verbose': Optional(Bool()), 
        'selection': Seq(Str())
    })
})
strictyaml.dirty_load(yaml_string, local_schema, allow_flow_style=True)
```

On my machine, the code fails with:

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-183-e30f444cc94a> in <module>
     10     })
     11 })
---> 12 strictyaml.dirty_load(yaml_string, local_schema, allow_flow_style=True)

~/miniconda3/envs/py36/lib/python3.6/site-packages/strictyaml/parser.py in dirty_load(yaml_string, schema, label, allow_flow_style)
    302     """
    303     return generic_load(
--> 304         yaml_string, schema=schema, label=label, allow_flow_style=allow_flow_style
    305     )
    306 

~/miniconda3/envs/py36/lib/python3.6/site-packages/strictyaml/parser.py in generic_load(yaml_string, schema, label, allow_flow_style)
    289         schema = Any()
    290 
--> 291     return schema(YAMLChunk(document, label=label))
    292 
    293 

~/miniconda3/envs/py36/lib/python3.6/site-packages/strictyaml/validators.py in __call__(self, chunk)
     15 
     16     def __call__(self, chunk):
---> 17         self.validate(chunk)
     18         return YAML(chunk, validator=self)
     19 

~/miniconda3/envs/py36/lib/python3.6/site-packages/strictyaml/compound.py in validate(self, chunk)
    156                 )
    157 
--> 158             value.process(self._validator_dict[yaml_key.scalar](value))
    159             key.process(yaml_key)
    160             chunk.add_key_association(key.contents, yaml_key.data)

~/miniconda3/envs/py36/lib/python3.6/site-packages/strictyaml/validators.py in __call__(self, chunk)
     15 
     16     def __call__(self, chunk):
---> 17         self.validate(chunk)
     18         return YAML(chunk, validator=self)
     19 

~/miniconda3/envs/py36/lib/python3.6/site-packages/strictyaml/compound.py in validate(self, chunk)
    156                 )
    157 
--> 158             value.process(self._validator_dict[yaml_key.scalar](value))
    159             key.process(yaml_key)
    160             chunk.add_key_association(key.contents, yaml_key.data)

TypeError: 'Optional' object is not callable
```

Why is that? My first idea was that I used `Optional` (or something else; maybe my YAML is wrong) incorrectly. 

However, I was not able to find any examples or documentation regarding the usage of `Optional`. So, I assumed that this validator wasn't finally implemented yet, hence my hotfix for it.

Could you clarify this part? I'm really confused about it.

**Comment by crdoconnor** [comment]
Like this:

```
yaml_string = '''
RegularizersModifierCube:
    num_iter: 5
    reg_search: add
    regularizer_parameters:
      regularizer_name: SmoothSparsePhiRegularizer
      tau_grid: []
    selection:
    - model.seed = 82019 and GoodinessMeasure -> max
    - model.seed = 322 and GoodinessMeasure -> max
    verbose: false
'''

import strictyaml
from strictyaml import Map, Optional, Any, Int, Bool, Seq, Str

local_schema = Map({
    'RegularizersModifierCube': Map({
        'num_iter': Int(), 
        'regularizer_parameters': Any(), 
        Optional('reg_search'): Any(), 
        Optional('strategy'): Any(), 
        Optional('tracked_score_function'): Any(), 
        Optional('verbose'): Bool(), 
        'selection': Seq(Str())
    })
})
strictyaml.dirty_load(yaml_string, local_schema, allow_flow_style=True)

```


Docs showing Optional are here: https://hitchdev.com/strictyaml/using/alpha/compound/optional-keys-with-defaults/

**Comment by bt2901** [comment]
I see. So I was using `Optional` wrong all along.

Thank you!

**Pull request closed without merging**
